---
title: "Coding for Reproducibility"
author: ["HVTN SDMC Reproducible Science Core"]
date: today
date-format: long
format: 
  revealjs:
    self-contained: true
    css: styles.css
    slide-number: true
execute:
  echo: true
  eval: false
  warning: false
  message: false
---


## Table of Contents

1. Coding for Portability
1. Coding for Numerical Stability 
1. On Reports
1. GitHub Primer
1. Writing Reproducibility Documents



# Coding for Portability

- Avoid setwd() or using absolute paths because they will break if someone else downloads the code and tries to run it

-	If the code sources a utility functions file, make sure that file is part of the code base, either at the project level or at the module level.

- If the code writes results to subdirectories, make sure the subdirectories exist through, e.g.
  ```r
  dir.create("output", showWarnings = FALSE, recursive=TRUE)
  ```
  - Nothing occurs if the folder already exists
  - The recursive option is needed if the path is more than one level deep



  
  
# Coding for Numerical Stability 

## R version

- R version matters for a number of reasons. The main reason is that it is easier to find the right versions of packages if we use the right version of R
- Ideally, we would use one of two R versions: 4.4.2 or 4.0.4, because these are two available and validated on SCHARP servers, which allow us to more easily reproduce results

## Handling rng for resampling {.compact .small}

```
# store the current rng state
saved.seed <- try(get(".Random.seed", .GlobalEnv), silent=TRUE) 
if (inherits(saved.seed,"try-error")) {set.seed(1); saved.seed <- get(".Random.seed", .GlobalEnv) }         

# resample and run analysis
seeds=1:B; names(seeds)=seeds
out=mclapply(seeds, mc.cores = numCores, FUN=function(seed) {   
  set.seed(seed+560)
  ...
})

# restore rng state 
assign(".Random.seed", saved.seed, .GlobalEnv)    
```

<br>

::: {style="font-size: 0.65em;"}
**Note**: `inherits(saved.seed,"try-error")` may occur if random number generator has not been called before.
:::


## Handling rng for resampling {.compact .small .no-scroll}

```
library(parallel)
library(doParallel)
library(foreach)
library(doRNG)

fun <- function(seed, n_iter, ...){
  # randomness before foreach()
  ...
  
  out <- foreach(i = 1:n_iter, .options.RNG = seed) %dorng% {
    # no set.seed() here; randomness for iteration i
    ...
  }
  
  # randomness after foreach()
  ...
}

registerDoParallel(cores = n_cores)
set.seed(1)  # master seed for the whole analysis
...
out <- fun(seed = 1001, n_iter = 1000, ...)
...
```

## renv

[Getting started with renv](https://hvtn-sdmc.github.io/reproducibility-core/using_renv.html)


# On Reports

## Report Reproduction Instructions Template {.compact .smaller #4part_template}

```bash
# a) obtaining the code
wget https://github.com/CoVPN/correlates_reporting2/archive/refs/tags/sanofi_stage2_R4.0.zip
unzip sanofi_stage2_R4.0.zip; rm sanofi_stage2_R4.0.zip
cd correlates_reporting2-sanofi_stage2_R4.0

# b) restore R package dependencies
R
    Sys.setenv(GITHUB_PAT = "xxxxxxxxxxxxxxxxxxxxxxxxxx") # use your personal github access token
    # install.packages("renv") # if renv has not been installed; optional if renv bootstrap process is triggered
    renv::restore()

# c) edit config.yml so that the data_cleaned field uder vat08_combined points to a local copy of vat08_combined_data_processed_20250417.csv
# c) edit all read.csv lines to read data from a local copy of vat08_combined_data_processed_20250417.csv

# d) generate report pdf
export TRIAL=vat08_combined
export stage=2    
cd cor_coxph
make 
```

<br>

**Note**: see next slide for more examples on (d)


## Report Reproduction Instructions Template {.compact .small}

For step (d),

- If there are only a few Rmd files to be rendered, an Rscript call is sufficient, e.g, 
''
Rscript -e "rmarkdown::render('controlled_risk_vaxart_mock.Rmd', output_file='controlled_risk_vaxart_mock_$(date +%Y%m%d).pdf')"
''
  
- Use a Makefile or a bash script to run analyses and generate reports, [example from cor_coxph](https://github.com/CoVPN/correlates_reporting2/blob/master/cor_coxph/Makefile)

- If high performance cluster/slurm is used and there are dependencies between steps, multiple scripts may be needed, [example from cop_exposureproximal](https://github.com/CoVPN/correlates_reporting2/blob/master/cop_exposureproximal/ensemble_severe_correlates/README.md)


## Report Naming {.compact}

- Include a date string in the report file name to show the date on which report was produced (e.g., filename ending 20251023 for October 23, 2025).  This can be done via, e.g. 
``
  Rscript -e "rmarkdown::render('cor_threshold_barda_mock.Rmd', output_file='cor_threshold_barda_mock_$(date +%Y%m%d).pdf')"
``  



## Recording code commit and data file in a report {.compact .small}

- All reports should include an appendix section that lists the code commit and the absolute path to the data file
- Copy the following Rmd chunk to your report Rmd (Replace ANALYSIS_READY_DATA_FILE_NAME with actual file name)

```` ```{r, echo = FALSE, message = FALSE, warning = FALSE, results='asis'} ````
````
commit_hash <- system("git rev-parse HEAD", intern = TRUE)
git_url <- sub("\\.git$", paste0("/commits/", commit_hash), system("git remote get-url origin", intern = TRUE))
cat("This report was built with code from [", sprintf("**[this commit](%s)**", git_url), "] and data from [", sprintf("**[this file](%s)**", ANALYSIS_READY_DATA_FILE_NAME), "].", sep="")
````
```` ``` ````


## Recording code commit and data file in a report {.compact .small}

- To have the code in the commit correspond to the code used to generate reports, follow the following steps:
  - Complete testing. This might involve generating reports to check results
  - Commit all code changes, including changes in package dependencies
  - Run the command if necessary to ensure renv.lock is synced: *renv::snapshot()*
  - Run report again, e.g., by *make report*
  
- In this process, the commit is often to a fork. Although not ideal, this serves as a critical fallback to ensure reproducibility





## Tips

- A standalone plot may be better done with a standalone script that hard-codes the logic. 



# GitHub Primer

## Two Branches of correlates_reporting2

- master
  - Code for NexGen
  - Use R 4.4 mostly
  - Contribute through fork and pull requests
  
- R40
  - Code for first gen
  - Use R 4.0 mostly
  - Con


## Creating a Fork of correlates_reporting2

- From https://github.com/CoVPN/correlates_reporting2, click the 'Fork' button, which is on the same row as the repo name 'correlates_reporting2'
- Make sure 'Copy the master branch only' is checked
- Click 'Create fork'


## Creating a Pull Request

- Go to the forked repo, e.g. https://github.com/user_name/correlates_reporting2/ (not CoVPN/correlates_reporting2)
- click the pull request tab
- click new pull request to merge updates from user_name/correlates_reporting2 to CoVPN/correlates_reporting2







# Writing Reproducibility Documents


## DataandCode.md file example {.smaller .compact}

```
# Summary of sharing of data and code for Zhang et al. “Distinct T-cell correlates of COVID-19 risk before and after a second booster in previously SARS-CoV-2 infected vs. naïve COVAIL trial participants ”

**Zhang et al.**

**March 12, 2026**

- All analyses are based on the analysis-ready data file covail_data_processed_20250818.csv unless otherwise specified.
- A copy of statistical reports are on the SCHARP network drive T:\covpn\COVAILcorrelates\analysis\correlates\reports\McElrathTcellsarticle

```

## DataandCode.md file example {.smaller .compact}

```
## Table 1
bAb-IgG Spike and nAb-ID50 antibody marker seroresponse frequencies.

**Statistical reports**: T:\covpn\p3005\reports\correlates_cor_tabular_vat08_combined_20250520.pdf

Collage mapping

* Data were extracted from pp. 75 (Table 2.57), 78 (Table 2.60), 96 (Table 2.78), and 107+108 (Table 2.84) of the report

To generate this report, follow instructions at [README](https://github.com/CoVPN/correlates_reporting2/tree/master/cor_tabular/README.md#sanofi_stage2_correlates) 

```

<br>

**Note**: see [this slide](#4part_template) for an instructions template.

## Levels of reproducibility testing

- Level 1: A report has been generated by someone other than the module’s author in an existing clone of the repo

- Level 2: A report has been generated following README.md in a new directory on a SCHARP server


